FROM  alphine

RUN apk update && \
    apk upgrade && \
    apk add vim

CMD	["vim"]

# FROM keyword. It tells docker, from which base image you want to base your image from.

#The RUN command is used to run instructions against the image.

# There can only be one CMD instruction in a Dockerfile
# The main purpose of a CMD is to provide defaults for an executing container.
